export const performanceSnapshotReportRow = {
  Control_Account_Manager: "",
  cpi_hgh_thlds_bchd: "0",
  cpi_low_thlds_bchd: "0",
  Perf_SS_P6_AC: "0",
  Perf_SS_ACWP: "0",
  Perf_SS_BAC: "0",
  Perf_SS_CPI: "0",
  Perf_SS_CV: "0",
  Perf_SS_EAC: "0",
  Perf_SS_ETC: "0",
  Perf_SS_EV: "0",
  PM_Adjusted_ETC: "0",
  Perf_SS_PV: "0",
  Perf_SS_SPI: "0",
  Perf_SS_SV: "0",
  Perf_SS_VAC: "0",
  cv_hgh_thlds_bchd: "0",
  cv_low_thlds_bchd: "0",
  D: "",
  uuu_obs_fullname: "",
  funding_type_p6udf: "",
  GROUP_NAME: "",
  pm_vac_hgh_thlds_bchd: "0",
  pm_vac_low_thlds_bchd: "0",
  pp_Cum_P6_AC: "0",
  pp_Cum_ACWP: "0",
  pp_cpi_hgh_thlds_bchd: "0",
  pp_cpi_low_thlds_bchd: "0",
  pp_cv_hgh_thlds_bchd: "0",
  pp_cv_low_thlds_bchd: "0",
  pp_Cum_EV: "0",
  pp_Cum_PV: "0",
  pp_spi_hgh_thlds_bchd: "0",
  pp_spi_low_thlds_bchd: "0",
  pp_sv_hgh_thlds_bchd: "0",
  pp_sv_low_thlds_bchd: "0",
  OBS_PUID: "",
  short_desc: "",
  spi_hgh_thlds_bchd: "0",
  spi_low_thlds_bchd: "0",
  sv_hgh_thlds_bchd: "0",
  sv_low_thlds_bchd: "0",
  TAB_NAME: "",
  uuu_user_loginname: "",
  vac_hgh_thlds_bchd: "0",
  vac_low_thlds_bchd: "0",
  uuu_cmwbs_code: "",
  uuu_P6ETCComputeType: "",
  uuu_cmwbs_name: "",
  uuu_P6WBSPath: "",
  wbs_type_p6udf: "",
 // PROJ_ID: "0"
} as const;

export type PerformanceSnapshotReportRow = typeof performanceSnapshotReportRow;

export type PerformanceSnapshotReport = PerformanceSnapshotReportRow[]; //for this report, the columns are already labelled the equivalent data elements
